### ISSUE TITLE
WMS GetFeatureInfo requests fail

### ISSUE THREAD

**Issue by asedgmen** [nci/gsky#14] opened 2018-05-18 05:23 UTC
GetFeatureInfo requests fail for all layers (at http://gsky.nci.org.au/ows), returning a 502 status response with error message:

> The proxy server received an invalid response from an upstream server

Following is an example GetFeatureInfo request that fails, generated from QGIS:

http://gsky.nci.org.au/ows?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetFeatureInfo&BBOX=-38.82254232573848185,145.65095678205847207,-38.07574253210549386,146.43161651595693229&CRS=EPSG:4326&WIDTH=830&HEIGHT=794&LAYERS=item:stddev&STYLES=&FORMAT=image/png&QUERY_LAYERS=item:stddev&INFO_FORMAT=text/html&I=492&J=486&FEATURE_COUNT=10

**Comment by edisonguo** [comment] 2018-05-30 03:30
@asedgmen @bje- I just tested it and this is not a bug but the original request missed the x and y parameters. x and y are required parameters documented here:
http://docs.geoserver.org/stable/en/user/services/wms/reference.html

For example, if I specify x = y = 0 in the following request, I get correct response.
http://gsky.nci.org.au/ows?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetFeatureInfo&x=0&y=0&BBOX=-38.82254232573848185,145.65095678205847207,-38.07574253210549386,146.43161651595693229&CRS=EPSG:4326&WIDTH=830&HEIGHT=794&LAYERS=item:stddev&STYLES=&FORMAT=image/png&QUERY_LAYERS=item:stddev&INFO_FORMAT=text/html&I=492&J=486&FEATURE_COUNT=10

**Comment by asedgmen** [comment] 2018-05-31 06:14
@edisonguo according to the WMS 1.1.1 and 1.3.0 specifications, and the linked GeoServer documentation, the use of the I and J parameters is valid for 1.3.0 WMS GetFeatureInfo requests (as per the example request).  X,Y params are required for WMS 1.1.1 GetFeatureInfo requests.

Can this issue please be reopened?

**Comment by edisonguo** [comment] 2018-05-31 10:13
okay i see. I think I and J are just used in the same way in 1.3.0 as X and Y in 1.1.1. If this is true, I'll simply add I and J in the http request.

**Comment by bje-** [comment] 2018-06-01 03:46
Fixed in master as well.

**Closed by bje-** 2018-06-01 03:46 UTC
Labels: invalid
